#!/usr/bin/env python3
"""Dump the command table of a live server as the notes-redisproto.md table.

РR4 makes identity a lookup in a closed table, and МR3 generates `norm_redis.c`
from that table — so the table has to come from the server itself, not from a
web page: `COMMAND DOCS` and `COMMAND INFO` know every command, every container
subcommand, and the flags that decide the "writing" and "blocking" bits.

  python3 cmdtable.py            markdown for the notes (default)
  python3 cmdtable.py --raw      one line per command, for diffing servers
  python3 cmdtable.py --stats    counts only
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from resp import Conn  # noqa: E402

# The flags that mean something to us. `write`/`blocking` are the two bits РR4
# asks for; the others are here because they explain why a command is special.
BITS = [("write", "w"), ("blocking", "b"), ("admin", "A"), ("pubsub", "P"),
        ("noscript", "-"), ("loading", "L"), ("fast", "f")]


def unwrap(v):
    """Decoded RESP → plain python (bytes → str, aggregates → list/dict)."""
    t, val = v
    if val is None:
        return None
    if isinstance(val, list):
        if t == b"%":
            return {unwrap(val[i]): unwrap(val[i + 1]) for i in range(0, len(val), 2)}
        return [unwrap(x) for x in val]
    if isinstance(val, bytes):
        return val.decode("latin1")
    return val


def commands(c):
    """{name: (arity, flags, [subcommands])} from COMMAND, one round trip."""
    c.send(b"*1\r\n$7\r\nCOMMAND\r\n")
    rows = unwrap(c.read(1)[0])
    out = {}
    for row in rows:
        if not row:
            continue
        name = row[0].upper()
        arity, flags = row[1], set(row[2] or [])
        subs = []
        # COMMAND's 10th field is the subcommand list (Redis 7+).
        if len(row) > 9 and isinstance(row[9], list):
            for sub in row[9]:
                if sub and isinstance(sub[0], str):
                    subs.append((sub[0].split("|")[-1].upper(),
                                 set(sub[2] or [])))
        out[name] = (arity, flags, sorted(subs))
    return out


def marks(flags):
    return "".join(ch for f, ch in BITS if f in flags) or "r"


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--md"
    c = Conn(log=False)
    info = unwrap(c.do("INFO", "server"))
    version = [l for l in info.split("\r\n") if l.startswith(("redis_version",
                                                             "valkey_version"))]
    cmds = commands(c)
    containers = {n: v for n, v in cmds.items() if v[2]}
    blocking = sorted(n for n, v in cmds.items() if "blocking" in v[1])
    writing = sorted(n for n, v in cmds.items() if "write" in v[1])
    total_subs = sum(len(v[2]) for v in containers.values())

    if mode == "--stats":
        print("server:      %s" % (version[0] if version else "?"))
        print("commands:    %d" % len(cmds))
        print("containers:  %d with %d subcommands" % (len(containers), total_subs))
        print("blocking:    %d  %s" % (len(blocking), " ".join(blocking)))
        print("writing:     %d" % len(writing))
        print("identities:  %d (commands + subcommands)" % (len(cmds) + total_subs))
        return
    if mode == "--raw":
        for n in sorted(cmds):
            arity, flags, subs = cmds[n]
            print("%-24s %-4s %s%s" % (n, arity, marks(flags),
                                       (" [" + " ".join(s for s, _ in subs) + "]") if subs else ""))
        return

    print("<!-- generated by tests/traces/redis/clients/cmdtable.py against %s -->"
          % (version[0] if version else "?"))
    print()
    print("%d commands, %d of them containers holding %d subcommands: "
          "%d identities in all." % (len(cmds), len(containers), total_subs,
                                     len(cmds) + total_subs))
    print()
    print("```")
    plain = sorted(n for n in cmds if n not in containers)
    line = []
    for n in plain:
        arity, flags, _ = cmds[n]
        line.append("%s%s" % (n, "" if "write" not in flags else "*"))
        if len(line) == 4:
            print("  " + "  ".join("%-20s" % x for x in line).rstrip())
            line = []
    if line:
        print("  " + "  ".join("%-20s" % x for x in line).rstrip())
    print("```")
    print()
    print("Container commands and their subcommands — the second word is part of the")
    print("identity here and only here (РR4):")
    print()
    print("| Container | Subcommands |")
    print("|---|---|")
    for n in sorted(containers):
        subs = ", ".join("`%s`" % s for s, _ in containers[n][2])
        print("| `%s` | %s |" % (n, subs))
    print()
    print("Blocking commands (the `LK_QO_BLOCKING` bit of РR10): %s."
          % ", ".join("`%s`" % b for b in blocking))


if __name__ == "__main__":
    main()
