#!/bin/sh
# The Redis command table has exactly one source of truth (PLAN-REDIS.md МR3,
# РR4): the table in docs/notes-redisproto.md §"The table", which
# tests/traces/redis/clients/cmdtable.py generated from a live server's own
# `COMMAND` output. src/norm/norm_redis_table.h is generated *from that section*
# and this script is both halves of keeping it so:
#
#   redis_table.sh --emit                     the generated header, on stdout
#   redis_table.sh <test_redis_cmd> [notes]   compare the compiled table with
#                                             the notes and fail on any drift
#
# The check runs against the *compiled* table (test_redis_cmd --dump prints what
# the binary actually holds), not against the generated file, so a hand-edit of
# either side surfaces here rather than in a metric label six months later.
#
# Regenerate after the notes change:
#
#   tests/unit/redis_table.sh --emit > src/norm/norm_redis_table.h
#
# Three kinds of bit end up in the table and they have different provenances,
# which is why the script says so in the header it writes:
#
#   * / blocking / container   the *server's*, quoted through the notes;
#   sub / session / ignore     *ours* — the semantic groups the handler acts on
#                              (РR6, РR8, РR14). They are listed below because
#                              no server flag names them: `SUBSCRIBE` and
#                              `UNSUBSCRIBE` share the pubsub flag with
#                              `PUBLISH`, and nothing on the wire marks `AUTH`
#                              as the command that moves a label.
set -eu

NOTES_DEF="$(dirname "$0")/../../docs/notes-redisproto.md"

# --- the semantic bits (ours) ----------------------------------------------
# One line per command: NAME<space>FLAGS, folded into the generated table.
semantic() {
    cat <<'EOF'
SUBSCRIBE SUBFAM|SUBON
PSUBSCRIBE SUBFAM|SUBON
SSUBSCRIBE SUBFAM|SUBON
UNSUBSCRIBE SUBFAM
PUNSUBSCRIBE SUBFAM
SUNSUBSCRIBE SUBFAM
SELECT SELECT
AUTH AUTH
HELLO HELLO
RESET RESET
PSYNC REPL
SYNC REPL
REPLCONF REPL
MONITOR MONITOR
MIGRATE SEC_KW
ACL|SETUSER SEC_RULE
CONFIG|SET SEC_PARAM
EOF
}

# --- the notes ---------------------------------------------------------------

# Plain commands: the fenced block right after the generator's comment, one
# name per token, `*` meaning the server's write flag.
notes_cmds() {
    awk '/^<!-- generated by tests\/traces\/redis\/clients\/cmdtable.py/ { g = 1 }
         g && /^```/ { f = !f; if (!f && seen) exit; seen = 1; next }
         g && f { for (i = 1; i <= NF; i++) print $i }' "$1"
}

# Containers and their subcommands, from the one `| Container | Subcommands |`
# table. Anchored on that header and ended by the first non-table line: the
# notes hold several other two-column tables of back-quoted upper-case words
# (the error dictionary, the type bytes), and a pattern loose enough to reach
# this one would swallow `CROSSSLOT` as a container.
notes_subs() {
    awk -F'|' '/^\| *Container *\| *Subcommands *\|/ { t = 1; next }
               t && !/^\|/ { exit }
               t && /^\| *`/ {
                   c = $2; gsub(/[ `]/, "", c)
                   n = split($3, subs, ",")
                   for (i = 1; i <= n; i++) {
                       s = subs[i]; gsub(/[ `]/, "", s)
                       if (s != "") print c, s
                   }
               }' "$1"
}

# The blocking list, intersected with the command set: the paragraph names
# `BLOCK` as an *argument* two lines later, and only a real command may take a
# bit from a sentence.
notes_blocking() {
    awk '/^Blocking:/ { p = 1 } p { print } p && /^$/ { exit }' "$1" |
        grep -oE '`[A-Z][A-Z0-9_]*`' | tr -d '`'
}

# The semantic flags of one identity, as a C expression. Subcommands can carry
# them too — `ACL|SETUSER` and `CONFIG|SET` are where a password reaches the wire
# without an `AUTH` in sight (РR6), and the identity that names them is the
# two-word one.
sub_flags() {
    sem=$(awk -v c="$2" '$1 == c { print $2 }' "$1")
    [ -n "$sem" ] || { echo 0; return; }
    out=""
    for s in $(printf '%s' "$sem" | tr '|' ' '); do
        out="$out | LK_REDIS_C_$s"
    done
    echo "${out# | }"
}

# --- the generated header ----------------------------------------------------

emit() {
    notes="$1"
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT

    notes_cmds "$notes" | sed 's/\*$/ W/' | awk '{ print $1, ($2 == "W" ? "W" : "-") }' \
        > "$tmp/plain"
    notes_subs "$notes" > "$tmp/subs"
    cut -d' ' -f1 "$tmp/subs" | sort -u | sed 's/$/ - C/' > "$tmp/containers"
    notes_blocking "$notes" | sort -u > "$tmp/blocking"
    semantic > "$tmp/semantic"

    # Every top-level command: the plain ones (with the write bit) plus the
    # containers, in one C-sorted list.
    { cat "$tmp/plain"; awk '{ print $1, "-" }' "$tmp/containers"; } |
        LC_ALL=C sort -k1,1 > "$tmp/cmds"

    ncmd=$(wc -l < "$tmp/cmds")
    nsub=$(wc -l < "$tmp/subs")
    ncont=$(wc -l < "$tmp/containers")

    cat <<EOF
/* SPDX-License-Identifier: GPL-2.0 */
/* GENERATED FILE — do not edit by hand.
 *
 *   tests/unit/redis_table.sh --emit > src/norm/norm_redis_table.h
 *
 * The identity table of РR4 (PLAN-REDIS.md МR3), generated from
 * docs/notes-redisproto.md §"The table" — which
 * tests/traces/redis/clients/cmdtable.py in turn generated from a live server's
 * own \`COMMAND\` output. One source of truth, two mechanical steps, and
 * tests/unit/redis_table.sh (the ctest \`redis_table\`) fails if the compiled
 * table and the notes ever disagree.
 *
 * $ncmd commands, $ncont of them containers holding $nsub subcommands, plus one
 * \`<container>|other\` per container and the global \`other\`: the closed set a
 * \`cmd\` label may take, and nothing else can reach one.
 *
 * Emitted clang-format-clean on purpose: the CI lint formats every .h under
 * src/, and a generated file that needed a hand pass afterwards would stop
 * being reproducible from one command.
 *
 * The write and blocking bits are the *server's*, quoted; the container bit is
 * the server's too. LK_REDIS_C_SUBFAM/SUBON/SELECT/AUTH/HELLO/RESET/REPL/
 * MONITOR are ours — the semantic groups the handler acts on (РR6, РR8, РR14),
 * which no server flag names. */
EOF
    echo
    echo "#define LK_REDIS_NCMD $ncmd /* top-level commands: entries [0, NCMD) */"
    echo "#define LK_REDIS_NSUB $((nsub + ncont)) /* subcommand entries, the \`|other\` ones included */"
    echo
    echo "/* [0, NCMD): the commands, C-sorted for the binary search."
    echo " * [NCMD, NCMD + NSUB): the subcommands, grouped per container and C-sorted"
    echo " *   inside each group, with the container's \`|other\` last (\`o\` sorts past"
    echo " *   every upper-case key, so the search cannot reach it and the container"
    echo " *   entry points at it by index)."
    echo " * The final entry is the global \`other\`: everything the table does not know"
    echo " *   — a module command, a fork's admin extension, a garbage first element. */"
    echo "static const struct redis_ent redis_tab[] = {"

    # Pass 1: the commands. A container's subcommand range is computed from the
    # group order, which is the container order in the sorted command list.
    off=$ncmd
    while read -r name write; do
        subs=$(awk -v c="$name" '$1 == c { print $2 }' "$tmp/subs" | LC_ALL=C sort)
        n=$(printf '%s' "$subs" | grep -c . || true)
        flags=""
        [ "$write" = "W" ] && flags="$flags | LK_REDIS_C_WRITE"
        grep -qx "$name" "$tmp/blocking" && flags="$flags | LK_REDIS_C_BLOCKING"
        if [ "$n" -gt 0 ]; then
            flags="$flags | LK_REDIS_C_CONTAINER"
            first=$off
            other=$((off + n))
            off=$((off + n + 1))
        else
            first=0
            other=0
        fi
        sem=$(awk -v c="$name" '$1 == c { print $2 }' "$tmp/semantic")
        if [ -n "$sem" ]; then
            for s in $(printf '%s' "$sem" | tr '|' ' '); do
                flags="$flags | LK_REDIS_C_$s"
            done
        fi
        flags=${flags# | }
        [ -n "$flags" ] || flags=0
        printf '    {"%s", %s, %d, %d, %d, %d, 0},\n' \
            "$name" "$flags" "$first" "$n" "$other" "${#name}"
    done < "$tmp/cmds"

    echo "    /* --- subcommands: \`CONFIG|GET\` is the identity, \`GET\` the key --- */"
    while read -r name write; do
        [ "$write" = "-" ] || true
        subs=$(awk -v c="$name" '$1 == c { print $2 }' "$tmp/subs" | LC_ALL=C sort)
        [ -n "$subs" ] || continue
        for s in $subs; do
            full="$name|$s"
            flags=$(sub_flags "$tmp/semantic" "$full")
            printf '    {"%s", %s, 0, 0, 0, %d, %d},\n' \
                "$full" "$flags" "${#full}" "$((${#name} + 1))"
        done
        full="$name|other"
        printf '    {"%s", 0, 0, 0, 0, %d, %d},\n' \
            "$full" "${#full}" "$((${#name} + 1))"
    done < "$tmp/cmds"

    echo '    /* Everything the table does not know (РR4): a module command, a'
    echo '     * fork-only admin command, or a first element that is not a verb at all. */'
    echo '    {"other", 0, 0, 0, 0, 5, 0},'
    echo "};"
}

# --- the check ---------------------------------------------------------------

# The notes, in the same `NAME flags` shape test_redis_cmd --dump prints: the
# three bits that came from the server, in the fixed order w, b, c, and `-` for
# none of them. The semantic bits are ours and are not compared — the notes have
# nothing to say about them, and a check that compared a file against itself
# would be no check at all.
notes_dump() {
    notes="$1"
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT

    notes_subs "$notes" > "$tmp/subs"
    notes_blocking "$notes" | sort -u > "$tmp/blocking"
    cut -d' ' -f1 "$tmp/subs" | sort -u > "$tmp/containers"

    notes_cmds "$notes" | while read -r tok; do
        name=${tok%\*}
        f=""
        [ "$name" != "$tok" ] && f="${f}w"
        grep -qx "$name" "$tmp/blocking" && f="${f}b"
        echo "$name ${f:--}"
    done
    while read -r c; do
        f=""
        grep -qx "$c" "$tmp/blocking" && f="b"
        echo "$c ${f}c"
        awk -v c="$c" '$1 == c { print c "|" $2, "-" }' "$tmp/subs"
        echo "$c|other -"
    done < "$tmp/containers"
    echo "other -"
}

case "${1:-}" in
--emit)
    emit "${2:-$NOTES_DEF}"
    ;;
*)
    BIN="${1:?usage: redis_table.sh --emit | redis_table.sh <test_redis_cmd> [notes.md]}"
    NOTES="${2:-$NOTES_DEF}"
    work=$(mktemp -d)
    trap 'rm -rf "$work"' EXIT
    "$BIN" --dump | LC_ALL=C sort > "$work/binary"
    notes_dump "$NOTES" | LC_ALL=C sort > "$work/notes"
    if cmp -s "$work/binary" "$work/notes"; then
        echo "ok   - the compiled table is the notes' table ($(wc -l < "$work/binary") identities)"
        exit 0
    fi
    echo "FAIL - src/norm/norm_redis_table.h vs docs/notes-redisproto.md" >&2
    echo "       ('<' only in the binary, '>' only in the notes):" >&2
    diff "$work/binary" "$work/notes" | grep '^[<>]' | head -40 >&2
    exit 1
    ;;
esac
